In [1]:
from dgp import *

# 1. Simulate or load data
sample_size = 800
min_degree = 1
max_degree = 1
adj = get_graph(sample_size, min_degree, max_degree, seed=2)

tau = np.array([-1.0, 0.50, -0.50])       # shape (3,)
rho = np.array([[0,0.1,0.2],
                [0.1,0,0.1],
                [0.2,0.1,0]])      # shape (3, 3), with 0s on the diagonal
nu = np.array([0.1,0,0,0.1,0,0,0.1,0,0]).reshape(3,3)       # shape (3, 3)
gamma = np.array([-1.00,0.50,0.10,0.20,0.05,0.25,-0.08,0.30])     # shape (8,)
beta = np.array([-0.30,-0.60,-0.20,-0.20,-0.05,-0.10,-0.01,0.40,0.01,0.20])     # shape (10,)

Y_chain, A_chain, L_chain = sample_network_chain(adj, tau, rho, nu, gamma, beta, R=30,
    burnin_R=10, seed=1)

Y_chain = Y_chain[::3]
A_chain = A_chain[::3]
L_chain = L_chain[::3]

100%|██████████| 40/40 [00:01<00:00, 30.95it/s]


In [4]:
[ret_i[cols_raw[i]] for i in range(len(cols_raw))]

[array([[ 0.29305888,  0.2035607 ,  0.2035607 , ...,  0.20994562,
          0.2035607 ,  0.2035607 ],
        [-0.35304393,  0.32645629,  0.43055738, ...,  0.31795403,
          0.31795403,  0.43055738],
        [-0.96024567,  0.32264745,  0.32264745, ...,  0.32264745,
          0.44544669,  0.32264745],
        ...,
        [ 0.25118471,  0.25118471,  0.25118471, ...,  0.25857843,
          0.25118471,  0.25118471],
        [ 0.25373302,  0.2464318 ,  0.2464318 , ...,  0.25373302,
          0.2464318 ,  0.34657662],
        [ 0.2035607 ,  0.29305888,  0.2035607 , ...,  0.20994562,
          0.29305888,  0.2035607 ]]),
 array([ 1.90043904, -0.35304393,  0.44544669,  0.38034633,  1.62321549,
         1.61009043,  0.34665989,  0.44668398,  0.36129278, -0.67739365,
         0.40410005,  0.41960038,  1.47562587,  0.35544539, -0.39392862,
         1.45013109,  0.39376258, -0.78778147,  0.49111992,  2.48869112,
         1.49668151,  1.42412787,  0.44544669,  0.32793849,  0.52819953,
        

In [ ]:
from drnet import doubly_robust
from run_pll import cols_raw

ret_i = doubly_robust(A_chain[-2], L_chain[-2], Y_chain[-2], adj, return_raw=True)
ret_array = np.zeros((ret_i[cols_raw[0]].shape[0], ret_i[cols_raw[0]].shape[1], len(cols_raw)))
for i in range(len(cols_raw)):
    ret_array[:, :, i] = ret_i[cols_raw[i]].copy()
print(ret_array.shape)

ValueError: could not broadcast input array from shape (800,) into shape (800,1000)

In [9]:
ret_i[cols_raw[i]]

array([ 1.90043904, -0.35304393,  0.44544669,  0.38034633,  1.62321549,
        1.61009043,  0.34665989,  0.44668398,  0.36129278, -0.67739365,
        0.40410005,  0.41960038,  1.47562587,  0.35544539, -0.39392862,
        1.45013109,  0.39376258, -0.78778147,  0.49111992,  2.48869112,
        1.49668151,  1.42412787,  0.44544669,  0.32793849,  0.52819953,
        0.36244909,  0.41104909,  0.39376258,  0.38971017, -0.65554083,
        0.39159003,  1.95844208, -0.42660283, -0.58524792,  2.01988487,
       -0.39248698, -0.33066046,  0.5083691 , -0.36184192,  0.41034969,
        1.77429017,  0.52819953,  0.38971017, -0.65482136,  1.63545343,
       -0.79122927,  0.40913863,  0.51319632,  0.4977605 , -0.4038125 ,
       -0.49901457,  0.46553424, -0.51896384,  0.45650839, -0.73877411,
        0.43944599, -0.61845294,  1.55527045,  0.39376258, -0.52342286,
        0.28789356,  0.30224439,  0.41627799,  0.33169768,  1.89676491,
        0.48051946,  0.47311491,  0.35544539,  0.56412429,  0.46

In [7]:
ret_array.shape, ret_i[cols_raw[i]].shape

((800, 1000, 4), (800,))

In [2]:
from autognet import fit_autog_models, extract_parameters_from_autog_models, prepare_features_outcome_model
import statsmodels.api as sm

def get_beta(adj_matrix, Y, A, L, treatment_allocation=0.5, R=10, burnin=5, seed=0):
    """
    Fit autognet models and evaluate causal effects using agc_effect.
    """
    np.random.seed(seed)
    models = fit_autog_models(Y, A, L, adj_matrix)
    tau, rho, nu, beta = extract_parameters_from_autog_models(models, adj_matrix)

    return beta

In [3]:
from tqdm import tqdm

betahats = []
for i in tqdm(range(len(Y_chain))):
    betahat = get_beta(adj, Y_chain[i], A_chain[i], L_chain[i], treatment_allocation=0.7, R=50, burnin=10, seed=1)
    betahats.append(betahat)

100%|██████████| 1000/1000 [00:17<00:00, 56.53it/s]


In [4]:
betahats[-1]

array([-0.39173937, -0.52787214,  0.15045679,  0.00440145, -0.08004167,
       -0.40050773, -0.05185024,  0.63315126,  0.14825143, -0.201992  ])

In [5]:
beta

array([-0.3 , -0.6 , -0.2 , -0.2 , -0.05, -0.1 , -0.01,  0.4 ,  0.01,
        0.2 ])

In [6]:
np.mean(np.array(betahats), axis=0) - beta

array([ 0.08010531, -0.0145634 , -0.00379152,  0.00883194, -0.00116777,
        0.00224138, -0.00691273,  0.00442347, -0.00247561, -0.21096924])

In [7]:
np.mean(np.mean(np.array(betahats), axis=0) - beta)

-0.014427816936012338